In [100]:
import numpy as np
import tensorflow as tf

In [50]:
a = tf.constant(5)

In [88]:
b = tf.constant(3)

In [89]:
div = tf.div(a, b)

In [90]:
mod = tf.mod(a, b)

In [52]:
add_two_number = tf.add(a, b)

In [56]:
matrix_a = tf.constant([1, 2], name='MTa')

In [57]:
matrix_b = tf.constant([[0, 1], [2, 3]], name="MTb")

In [58]:
add_matrix = tf.add(matrix_a, matrix_b, name="add_matrix")

In [60]:
mul_matrix = tf.multiply(matrix_a, matrix_b, name="mul_matrix")

In [63]:
zeros_matrix = tf.zeros([2,4], tf.int32)

In [65]:
zeros_like_matrix = tf.zeros_like(matrix_b)

In [67]:
zeros_one = tf.ones([3, 4], tf.float32)

In [69]:
fill_matrix = tf.fill([3, 5], 7)

In [71]:
linspace = tf.linspace(10.0, 100.0, 20)

In [75]:
range_sequences = tf.range(3, 30, 2)

In [76]:
limit_sequences = tf.range(20)

In [78]:
random_normal = tf.random_normal([3, 4], mean=0.0, stddev=1.0, dtype=tf.float32)

In [79]:
truncated_normal = tf.truncated_normal([3, 4], mean=0.0, stddev=1.0, dtype=tf.float32)

In [81]:
random_uniform = tf.random_uniform([3, 4], minval=0, maxval=12, dtype=tf.float32)

In [82]:
# random_crop = tf.random_crop(10, [3, 4])

ValueError: Dimensions must be equal, but are 0 and 2 for 'random_crop/GreaterEqual' (op: 'GreaterEqual') with input shapes: [0], [2].

In [91]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./example', sess.graph)
    print (sess.run(add_two_number))
    print (sess.run(add_matrix))
    print (sess.run(mod))
    print (sess.run(div))
    print ("------------------------------")
    print (sess.run(mul_matrix))
    print (sess.run(zeros_matrix))
    print (sess.run(zeros_like_matrix))
    print (sess.run(zeros_one))
    print ("---------------------------")
    print (sess.run(fill_matrix))
    print (sess.run(linspace))
    print (sess.run(range_sequences))
    print (sess.run(limit_sequences))
    print ("------------random-------------")
    print ("random normal [3, 4]; mean = 0.0; stddev = 1.0")
    print (sess.run(random_normal))
    print ("truncated normal [3, 4]; mean = 0.0; stddev = 1.0")
    print (sess.run(truncated_normal))
    print ("random uniform [3, 4] min = 0; max = 12")
    print (sess.run(random_uniform))

8
[[1 3]
 [3 5]]
2
1
------------------------------
[[0 2]
 [2 6]]
[[0 0 0 0]
 [0 0 0 0]]
[[0 0]
 [0 0]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
---------------------------
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[  10.           14.73684216   19.47368431   24.21052551   28.94736862
   33.68421173   38.42105103   43.15789413   47.89473724   52.63158035
   57.36842346   62.10526276   66.84210205   71.57894897   76.31578827
   81.05263519   85.78947449   90.52631378   95.26316071  100.        ]
[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
------------random-------------
random normal [3, 4]; mean = 0.0; stddev = 1.0
[[ 0.96713251  1.35174072  1.43701696  0.22278281]
 [ 0.61102855 -0.48397729  1.13979113  0.21701425]
 [-0.91737169 -0.56160092  1.27894962 -1.2177856 ]]
truncated normal [3, 4]; mean = 0.0; stddev = 1.0
[[ 0.01868468  1.70096838  0.45058289 -1.08556962]
 [-0.12861909 -0.6898753   0.78613704 -0.150

In [55]:
writer.close()

In [92]:
t_0 = 10
zeros_like = tf.zeros_like(t_0)

In [95]:
ones_like = tf.ones_like(t_0)

In [97]:
t_1 = ['apple', 'peach', 'banana']

In [98]:
t_1_zeros = tf.zeros_like(t_1)
t_1_ones = tf.ones_like(t_1)

TypeError: Expected string, got 1 of type 'int' instead.

In [96]:
with tf.Session() as sess:
    print(sess.run(zeros_like))
    print(sess.run(ones_like))

0
1


In [101]:
tf.int32 == np.int32

True

In [103]:
np_tf = tf.ones([2, 2], np.float32)

In [105]:
with tf.Session() as sess:
    print(sess.run(np_tf))

[[ 1.  1.]
 [ 1.  1.]]
