In [1]:
import cv2

In [2]:
image = cv2.imread("holly.jpg")
cv2.imshow("original", image)
cv2.waitKey(0)

32

In [3]:
print(image.shape)

(1349, 1080, 3)


In [4]:
type(image)

numpy.ndarray

In [5]:
# resizing an image
r = 100.0 / image.shape[1]
dim = (100, int(image.shape[0] * r))

In [6]:
resized = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)

In [7]:
print(resized)

[[[151 169 180]
  [150 168 179]
  [149 167 178]
  ..., 
  [131 153 165]
  [131 153 164]
  [132 154 165]]

 [[151 169 180]
  [150 168 179]
  [150 168 179]
  ..., 
  [131 153 165]
  [131 153 165]
  [132 154 165]]

 [[151 169 180]
  [150 168 179]
  [150 168 179]
  ..., 
  [131 153 165]
  [131 153 165]
  [133 155 167]]

 ..., 
 [[ 95 113 129]
  [ 82  99 113]
  [ 79  95 109]
  ..., 
  [ 78  94 108]
  [101 112 121]
  [107 117 126]]

 [[ 88 104 118]
  [ 95 113 130]
  [ 97 114 131]
  ..., 
  [ 73  94 112]
  [ 76  94 109]
  [100 111 121]]

 [[107 123 139]
  [100 118 135]
  [103 121 138]
  ..., 
  [ 76  95 115]
  [ 74  93 112]
  [ 75  93 109]]]


In [8]:
cv2.imshow("resized", resized)

In [9]:
cv2.waitKey(0)

32

In [10]:
# rotating an image
(h, w) = image.shape[:2]

In [11]:
print(h)

1349


In [12]:
print(w)

1080


In [13]:
center = (w / 2, h / 2)

In [14]:
M = cv2.getRotationMatrix2D(center, 180, 0.3)

In [16]:
rotated = cv2.warpAffine(image, M, (w, h))
cv2.imshow("rotated", rotated)

In [17]:
cv2.waitKey(0)

32

In [18]:
# crop an image
cropped = image[70:170, 440:899]

In [19]:
cv2.imshow("cropped", cropped)

In [ ]:
cv2.waitKey(0)

In [ ]:
cv2.imwrite("abc.png", cropped)